### ISSUE TITLE
Getting 404 ResourceNotFound for GiftCard and Discount resources

### ISSUE THREAD

**Issue by kokeshii** [Shopify/shopify_python_api#163]
We have a Shopify+ account, and trying to use the API Resources for `GiftCard` and `Discount` results in a ResourceNotFound exception:

```
pyactiveresource.connection.ResourceNotFound: Not Found: https://<shop>.myshopify.com/admin/gift_cards.json
```

Also, visiting the above URL (with the actual value for <shop>) on my browser displays the resource in JSON format correctly.

**Comment by jamiemtdwyer** [comment]
Hey kokeshii,

GiftCard and Discount APIs are restricted to Shopify Plus users. 404 is the expected response here. Previously, this response was a 501 but has recently changed to a 404 for semantical reasons.

If you're working with a Shopify Plus client, I would suggest coordinating with the client and their merchant success manager in order to be provisioned with a test store and credentials in order to exercise these endpoints.

**Comment by orenmazor** [comment]
@jamiemtdwyer what credentials do we need to have access to the Plus endpoints (checkout, discount, and gift_card)? I've enabled everything and still just 404s.

**Comment by jamiemtdwyer** [comment]
Hey @orenmazor, you need to have the merchant coordinate with their account manager at Shopify in order to provision the access to the private application.

**Comment by orenmazor** [comment]
so its not a thing that can get created from the admin. it comes from internal_services? gotcha

**Comment by clement911** [comment]
Why does it need to be activated explicitely?
The api docs should be updated to indicate this... is this also the case for other Plus APIs like User and Multipass?

**Comment by orenmazor** [comment]
The api docs definitely should be more clear.

And it is not the case for anything else iirc
