### ISSUE TITLE
API Request ISO 8601 Datetime Fomat

### ISSUE THREAD

**Issue by coler-j** [Shopify/shopify_python_api#175]
The Shopify API reference says:

> **updated_at_min**
> Show products last updated after date (**format: 2014-04-25T16:15:47-04:00**)

If I have a datetime object when making an API call, do I need to convert the datetime to a string of ISO 8601 format prior to making the request?

i.e. do I need to do this?

```
min_date = timezone.now()
shopify.Product.count(created_at_min = str(min_data.isoformat()))
```

My request would look like this then:

`https://[store-url].myshopify.com/admin/products/count.json?updated_at_min=2017-01-29T14%3A43%3A27-05%3A00`

Versus this (if I pass the unformatted datetime object in):

`https://[store-url].myshopify.com/admin/products/count.json?updated_at_min=2016-12-10+14%3A43%3A27-05%3A00`

(If so, why doesn't the Shopify Python API handle this conversion automatically, seems kind of silly?)

**Comment by jamiemtdwyer** [comment]
The Shopify API actually does accept several date formats, but it's always safest to use the formatted that is documented in the API documentation (ISO 8601), as this is guaranteed to continue working in the future.

> (If so, why doesn't the Shopify Python API handle this conversion automatically, seems kind of silly?)

Because the bulk of the functionality of this library is for wrapping HTTP requests using pyactiveresource  - it is largely a port of https://github.com/shopify/shopify_api. However, PRs are accepted and if you'd like to add some helper functions for dates, please feel free to contribute. :)

**Comment by cal97g** [comment]
Me trying to remove enough of my brain to have a brain small enough where building something in python like it's ruby makes sense

![CLVQg1oUYAAjPpG](https://user-images.githubusercontent.com/1664656/230786454-57d80b6a-dd1d-49c0-b667-ded3f64ae5a7.jpg)
