### ISSUE TITLE
More examples in documentation

### ISSUE THREAD

**Issue by wowkin2** [Shopify/shopify_python_api#218]
Please provide more documentation with examples: how to find products/variants by some attribute for example price, sku, product_id, etc.

**Comment by jamiemtdwyer** [comment]
Product id is the product's primary lookup value – you can pass this directly to the `find` method.

You can apply a filter to the index endpoint as described [here ](https://help.shopify.com/api/reference/product#index) in order to search by certain attributes such as `product_type`.  Searching by `price` or `sku` is not possible, and this functionality must be implemented within your application by indexing the records and searching locally.

As for examples, I suggest you look at the tests within this repo and read up on [ActiveResource](https://apidock.com/rails/ActiveResource/Base) if you are not familiar with the patterns used.

I'm going to close this as there are several issues outlining the need for better documentation and I do plan to address this within this repo.
