### ISSUE TITLE
session.request_token

### ISSUE THREAD

**Issue by KevinMind** [Shopify/shopify_python_api#231]
There is a method to make the request and get the token for you. Pass all the params received from the previous call (shop, code, timestamp, signature) as a dictionary and the method will verify the params, extract the temp code and then request your token:

I"m including a dictionary 

    params = {
        'shop': request.GET.get('shop'),
        'code': request.GET.get('code'),
        'timestamp': request.GET.get('timestamp'),
        'hmac': request.GET.get('hmac')
    }

No matter what I do, I fail the validate_params() method.

"Invalid HMAC: Possibly malicious login"

IS this the correct object to pass to this method? I have values for all the request params, and the app actually shows up as installed even though the method fails. If I can figure out how to get this working, I'll submit a pr with updates to readme so formatting this request for future peeps will be easier.

Using django 2.0 python 3.6

**Comment by jamiemtdwyer** [comment]
It looks are you creating a dictionary based on these selective parameters
that you have chosen.

You need to provide all of the parameters that were passed to your
application from Shopify.

From the README:

```
Pass all the params received from the previous call (shop, code, timestamp,
signature) as a dictionary
```

Hope this helps.

On Feb 1, 2018 01:09, "Kevin Meinhardt" <notifications@github.com> wrote:

There is a method to make the request and get the token for you. Pass all
the params received from the previous call (shop, code, timestamp,
signature) as a dictionary and the method will verify the params, extract
the temp code and then request your token:

I"m including a dictionary

params = {
    'shop': request.GET.get('shop'),
    'code': request.GET.get('code'),
    'timestamp': request.GET.get('timestamp'),
    'hmac': request.GET.get('hmac')
}

No matter what I do, I fail the validate_params() method.

"Invalid HMAC: Possibly malicious login"

IS this the correct object to pass to this method? I have values for all
the request params, and the app actually shows up as installed even though
the method fails. If I can figure out how to get this working, I'll submit
a pr with updates to readme so formatting this request for future peeps
will be easier.

Using django 2.0 python 3.6

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Shopify/shopify_python_api/issues/231>, or mute the
thread

**Comment by KevinMind** [comment]
I tried that originally passing request.GET, same result. Here is exactly the code I'm running.

my assumptions are:

1. api_key is the app api_key in shopify 
2. and secret is the secret key in shopify 

```
from django.http import HttpResponse
from django.shortcuts import redirect
import shopify
import os

# INSTANTIATE THIS APPS CREDENTIALS TO SHOPIFY
shopify.Session.setup(api_key=os.environ.get('SHOPIFY_API_KEY'), secret=os.environ.get('SHOPIFY_SECRET_KEY'))

def login(request):
    if request.GET.get('shop'):
        return authenticate(request)
    return HttpResponse("login please")

def authenticate(request):
    shop = request.GET.get('shop')
    if shop:

        # start session
        session = shopify.Session("{}.myshopify.com".format(shop))

        scope = ['read_products', 'write_products']
        # redirects to finalize(request) below
        redirect_uri = 'http://localhost:8000/finalize/'
        permission_url = session.create_permission_url(scope, redirect_uri)

        return redirect(permission_url)

def finalize(request):
    shop_url = request.GET.get('shop')

    session = shopify.Session(shop_url)
    token = session.request_token(request.GET)

    print(request.GET)
    request.session['shopify'] = {
        "shop_url": shop_url,
        "access_token": token
    }
    
    return HttpResponse(token)
```

I don't see a very good way of debugging this other than downloading the shopify api code and running it locally. Anything look wrong here?

**Comment by jamiemtdwyer** [comment]
Nothing immediately stands out to me.

[Here's a simple example of my own written in Flask](https://gist.github.com/jamiemtdwyer/b6c8af90277869fe899c130ddf0ffcb9) that might help you identify where you went wrong.

`token = session.request_token(request.GET)`

This is the line where the package actually [attempts to verify the request digest](https://github.com/Shopify/shopify_python_api/blob/9c79c9680cd4116f13830efea9fa16a549ad540d/shopify/session.py#L51-L56), so if you can attach a debugger and step in, you might be able to see exactly why there is a mismatch.

Btw, this looks a bit suspect to me:

```
session = shopify.Session("{}.myshopify.com".format(shop))
```

The `shop` param coming in will already be appended by `myshopify.com`, so this looks like it could result in something like `my-shop.myshopify.com.myshopify.com`.

The only difference that stands out to me is that I'm storing my `shopify.Session` object in memory and retrieving it in my callback route while you're defining a new instance of the resource in yours. It doesn't seem to me like that should make a major difference though, but I might be overlooking something.

**Comment by KevinMind** [comment]
I ran session.py locally and found out that in fact, I was using the wrong secret key... It works perfectly now.
