### ISSUE TITLE
 Reading shop metafields: Discrepancy between AJAX call and backend view behavior 

### ISSUE THREAD

**Issue by aphelionz** [Shopify/shopify_python_api#260]
I'm using the https://github.com/discolabs/django-shopify-auth/issues/45 with this, so I cross-posted there, but I'm asking here as well.

Getting the list of shop metaifleds works great if running on the server in a simple Django view:

```
def my_view(request):
    with request.user.session:
        shop = shopify.Shop().current()
        print(shop.metafields())    # returns [(metafield(1232543), metafields(143534534), etc]
```

However, if I do something like this (don't panic, I'm just experimenting) in an AJAX handler, it returns an empty array.

```
@csrf_exempt
def proxy_request(request):
    shop_user = AuthAppShopUser.objects.get(myshopify_domain=site)
    user = auth.authenticate(request=request, myshopify_domain=site, token=shop_user.token)
    if user:
        auth.login(request, user)
        
        with request.user.session:
            shop = shopify.Shop().current()
            print(shop.metafields())   # returns []
```

Thank you for any insight!

**Comment by dave4jr** [comment]
@aphelionz  Mark, no disrespect at all, but I don't think you will get a response to this question from these guys because it's not really related to this library. Yours views.py in a django app takes a request that is routed from urls.py, and returns a response. The view function gets run exactly the same in both instances, the only difference is how the response from the view is generated. In this case, django just gets a request, it doesn't know what ajax is. In the first instance  you are running the logic and rendering a dango template (you didn't include this code but i can infer) with context variables you want injected into that template. In the second example, the same logic is run but instead of rendering a django template, which will cause a browser refresh, you are just returning the JSON response back to your ajax function. So to reiterate, there is no difference in how the logic runs on both of these views. The issue lies in your code. In order to compare code, your logic needs to be the same. You have a bunch of extra code in the second instance . You have access to the same request variable, why are you doing this 2 different ways?

**Comment by aphelionz** [comment]
I'm printing out the output of the shop.metafields() function before the Django response handler even touches it. I'm not talking about what's returned to the client, I'm talking about what the python, at that line, is expressing. Not what's downstream.

**Comment by dave4jr** [comment]
Right, that is what I was saying. Because you are printing out before the response, those views are exactly the same. Your question should be "Difference between Backend View and Backend View" because the only thing that differentiates an AJAX Call and what you are referring to as "Backend View" is the response, and you are printing out before the response, so they are equivalent. Does that make sense?

The second snippet you have referred to is a simple view, it's exactly the same as the first view except the render function that you at the bottom which does not affect the code above it. 

If you are getting the right metafields you need in the first view, why can't you just do the same thing for your AJAX view? You have access to the same request variable. 
`
@csrf_exempt
def proxy_request(request):
    with request.user.session:
        shop = shopify.Shop().current()
        print(shop.metafields())
`

I've never used that django app but from reading the github page, it stores the shop as the user, so what's most likely happening in your second view logic is you are changing the current shop based up the user and then returning no metafields. Just use the code from the first view in your AJAX view.
