### ISSUE TITLE
ITP 2.0 support 

### ISSUE THREAD

**Issue by domWinter** [Shopify/shopify_python_api#284]
Hey,

as [ITP-Impact](https://help.shopify.com/en/api/guides/itp-impact) states their is a workaround needed for embedded shopify apps in Safari 12.0+ dealing with webkits ITP 2.0 implementation.
Workarounds for ruby and nodejs are already implemented but not for python.
Is there a plan for implementing this in shopify_python_api as well?

Best regards
Dominik

**Comment by jamiemtdwyer** [comment]
I'm pretty confident that this falls outside the scope of this library, which is intended to provide a connection to the Shopify API rather than provide any sort of framework to build an application.

There is [shopify_django_app](https://github.com/shopify/shopify_django_app) but it hasn't been maintained in 7 (!) years. Unfortunately, I don't have the time to take over development on that library since I'm actually maintaining this repo in my spare time.

**Comment by domWinter** [comment]
Hey, 

thanks you for your quick reply!
I am currently working on a workaround for this.

Best regards
