### ISSUE TITLE
How to request /admin/collection/id/products.json endpoint

### ISSUE THREAD

**Issue by stlk** [Shopify/shopify_python_api#380]
I'm trying to [migrate](https://shopify.dev/tutorials/migrate-from-collect-endpoint-to-collections) to the new endpoint, but I couldn't find it. Is it already implemented? If yes, could you share some code example please.

This is our current implementation:

```python
    collection_updated_at = parse_datetime(collection_updated_at_str)
    with shop.session:
        collects = shopify.Collect().find(collection_id=collection_id)
        [
            get_collection_ids.invalidate(shop, collect.product_id)
            for collect in collects
            if parse_datetime(collect.updated_at) == collection_updated_at
        ]
```

Thank you :)

**Comment by mllemango** [comment]
Hi @stlk, we're sorry but the python api at this time doesn't have the new endpoint implemented yet. We'll keep this open in order to track the issue further.

**Comment by mllemango** [comment]
Hey, looked into this a bit more. It seems that "Collections" have always existed as SmartCollections and CustomCollection in the api. If you know which sort of collections you are normally interacting with you can use one of these implementations, otherwise, you can implement the main collection yourself like this
`class Collection(shopify.ShopifyResource, mixins.Metafields, mixins.Events):
    pass`

**Comment by samLozier** [comment]
I got stuck on this myself. In case anyone else ends up here with the same issue, it's as easy as this: 
`c = shopify.SmartCollection.find(collectionID)`
`c.products()`
