### ISSUE TITLE
Pagination bug: not all fields are returned after the first page for shopify.Variant.find

### ISSUE THREAD

**Issue by travis-st** [Shopify/shopify_python_api#384]
SDK Version 7.0.1
API Version 2020-01

I posted a [thread](https://community.shopify.com/c/Shopify-APIs-SDKs/Why-would-a-product-variant-not-have-a-product-ID/m-p/723232#M48477) about this in the community and staff member hassain did testing and found that it's a problem with the SDK. 

Code:

```
next_url = None
while True:
    if next_url:
        shopify_variants = shopify.Variant.find(from_=next_url)
    else:
        shopify_variants = shopify.Variant.find(limit=1, fields='id,product_id',)

    for shopify_variant in shopify_variants:
        print('{},{}'.format(next_url, shopify_variant.to_dict()))

    if next_url:
        # show only the second page
        break

    if shopify_variants.has_next_page():
        next_url = shopify_variants.next_page_url
    else:
        break
```

Outputs
```
None,{'id': 29546499473, 'product_id': 8595877265}
{$next_url},{'id': 29546499537}

```

Basically, when the SDK grabs the second page, the product_id isn't returned. I found this to be the case whether or not the `fields` were specified or not.

**Comment by mkevinosullivan** [comment]
Thanks Travis for the issue report, will pass it to the team to take a look and try to fix as soon as possible.

**Comment by edelooff** [comment]
We're currently running into the same problem. It appears the origin for this problem is in `ShopifyResource.__init__` ([shopify/base.py](https://github.com/Shopify/shopify_python_api/blob/master/shopify/base.py#L178)) where there is an explicit check whether `prefix_options is None`. This is false for the first page, but becomes true for the second.

The reason for that is in `ActiveResource._find_every` ([pyactiveresource/activeresource.py](https://github.com/Shopify/pyactiveresource/blob/master/pyactiveresource/activeresource.py#L507)), which explicitly sets `prefix_options = None` in case the find operation is triggered from a `from_` URL. This is exactly how the PaginatedCollection retrieves the next page.

If the conditional in `ShopifyResource.__init__` is merely intended to check "have prefix options been provided" then a better initial value could be used (`UNSET = object()`) and tested against. It could also be that pyactiveresource is wrong to set it to None rather than an empty dictionary, and that this needs to be changed instead.

Both changes appear to make the specific case of multi-page variant lookups work, but I haven't delved into further side-effects.

**Comment by edelooff** [comment]
To work around this bug we've created a subclass of the Variant that checks whether `prefix_options` have been provided by comparing against an initial value as described above:

```python
class Variant(shopify.Variant):
    INITIAL = object()

    def __init__(self, attributes=None, prefix_options=INITIAL):
        if attributes is not None and prefix_options is self.INITIAL:
            prefix_options, attributes = self.__class__._split_options(attributes)
        return super(shopify.ShopifyResource, self).__init__(attributes, prefix_options)
```

This will allow for multiple pages to be pulled in and processed successfully using either `PaginatedCollection` or `PaginatedIterator`.

**Comment by dsoprea** [comment]
Bump.

The suggested hack is not generally applicable to all interfaces/nouns.

https://github.com/Shopify/shopify_python_api/issues/384#issuecomment-643333016

**Comment by thecodepixi** [comment]
Hey folks! This issue is very outdated, and I believe has actually been resolved in a newer version of the library, so I'll be closing this. However, if you still experience issues with pagination, please feel free to open a new issue.
