### ISSUE TITLE
Oauth error invalid_request: The redirect_uri is not whitelisted using shopify_django_app

### ISSUE THREAD

**Issue by occamssafetyrazor** [Shopify/shopify_python_api#452]
# Issue summary

Attempting to authorize an app using a clean install of [shopify_django_app](https://github.com/Shopify/shopify_django_app) yields the error: 
"Oauth error invalid_request: The redirect_uri is not whitelisted" 

The url of the 400 oauth error:
https://marketmath.myshopify.com/admin/oauth/authorize?client_id=7726527dfe7bcdf9edba8162459173bd&scope=read_products&redirect_uri=http://localhost:8000/shopify/finalize/&state=3f5f3afe548c57324a81a38a4ad7e6

App Setup settings:
App URL
http://localhost:8000/
Allowed redirection URL(s):
http://localhost:8000/shopify/finalize/

## Expected behavior

For the app to authorize. I was able to authorize successfully though the [Shopify tutorial](https://shopify.dev/tutorials/build-a-shopify-app-with-node-and-react/embed-your-app-in-shopify) using koa-shopify-auth.

## Actual behavior

Oauth error invalid_request: The redirect_uri is not whitelisted

https://marketmath.myshopify.com/admin/oauth/authorize?client_id=7726527dfe7bcdf9edba8162459173bd&scope=read_products&redirect_uri=http://localhost:8000/shopify/finalize/&state=3f5f3afe548c57324a81a38a4ad7e6

## Steps to reproduce the problem

1. Install and run [shopify_django_app](https://github.com/Shopify/shopify_django_app) using the setup instructions.
2. Go to http://localhost:8000 and enter the shopify test store subdomain.
3. Click install

## Reduced test case

I'm unsure how to create a reduced test case with an error from an external API and the django framework. There is a tunnel open on be4f096773f3.ngrok.io so you can view the error (App URL and redirection URLs updated to ngrok).

## Specifications

- `shopify_python_api` version: 8.0.1
- `pyactiveresource` version: 2.2.1
- Shopify API version used (e.g. `'2020-07'`): 2020-10

**Comment by paulomarg** [comment]
Hi @occamssafetyrazor, you're seeing this issue because you're telling Shopify to use an HTTP URL to access your app, which isn't supported - you need to provide an HTTPS address to be able to use apps.

The easiest way to set up HTTPS support is to run [ngrok](https://ngrok.com/), which creates a tunnel that maps an address to your localhost that Shopify can access.

If you download ngrok and run `/path/to/download/ngrok http 8000` you'll get an HTTPS address. You can then use that address in your app configuration and you'll be able to authenticate.

Hope this helps!

**Comment by occamssafetyrazor** [comment]
Thank you @pauldowman! That worked.
