### ISSUE TITLE
Update of inventory quantity won't be saved 

### ISSUE THREAD

**Issue by taminobaumann** [Shopify/shopify_python_api#490]
# Issue summary

Write a short description of the issue here ↓
I want to update the inventory quantity of a product variant which is already tracked by Shopify.
In my case I want to change the quantity from 1 to 2.

## Expected behavior

The update should be saved to Shopify after I ran this code.

```
session = shopify.Session(SHOP_URL, API_VERSION, APP_PASSWORD)
shopify.ShopifyResource.activate_session(session)

product = shopify.Product.find(product_id)
variants = product.variants
variant = variants[0]
print(variant.inventory_quantity)
variant.inventory_quantity = 2
print(variant.inventory_quantity)
variant.save()
print(variant.inventory_quantity)

shopify.ShopifyResource.clear_session()
```

## Actual behavior

After the save method ran, the quantity is reset to the previous state and not updated.

Output of the above code block:

```
1
2
1
```

**Comment by mkevinosullivan** [comment]
👋🏻 I don't think you can update `inventory_quantity` that way any more (since `2020-04`) - please see the [API reference](https://shopify.dev/docs/admin-api/rest/reference/products/product-variant) and the [tutorial](https://shopify.dev/tutorials/manage-product-inventory-with-admin-api) on managing product inventory.

**Comment by taminobaumann** [comment]
Thank you @mkevinosullivan! 🙂
