### ISSUE TITLE
2021-10 API Version is not recognized

### ISSUE THREAD

**Issue by noahsark769** [Shopify/shopify_python_api#542]
# Issue summary
Shopify API version 2021-10 was released 7 days ago on October 1st. However, this version is not listed yet in api_versions.py, so you can't query against it (the library raises a VersionNotFoundError). It would be good to add this in and create a new release so this library can be used to query models from the newer API version (metafieldDefinitions is an example of an API only available in 2021-10).

## Expected behavior
Using 2021-10 should not raise VersionNotFoundError on any request

## Actual behavior
VersionNotFoundError is raised

**Comment by sagar-wal** [comment]
Yes, this problem is causing Shopify to give a warning to use the ADMIN API latest version.


![deprecated-api-call-blurred](https://user-images.githubusercontent.com/53569839/137456208-77ad8344-1108-4dfd-8b28-a7b73310afcc.png)


The latest versions need to be added in api_versions.py. But it'd be better to follow @noahsark769's solution to add formatting-based validation.

**Comment by mllemango** [comment]
Closing since the version has been added
