### ISSUE TITLE
Add inventoryAdjustQuantities/inventoryActivate/inventoryDeactivate bulk mutation operation

### ISSUE THREAD

**Issue by plesoiucosmin** [Shopify/shopify_python_api#724]
There does not seem to be a way to update/activate/deactivate a location inventories by using a [bulkOperationRunMutation](https://shopify.dev/docs/api/admin-graphql/latest/mutations/bulkoperationrunmutation)
Operations to add bulk option:
* [inventoryActivate](https://shopify.dev/docs/api/admin-graphql/2024-07/mutations/inventoryActivate)
* [inventoryDeactivate](https://shopify.dev/docs/api/admin-graphql/2024-07/mutations/inventoryDeactivate)
* [inventoryAdjustQuantities](https://shopify.dev/docs/api/admin-graphql/2024-07/mutations/inventoryAdjustQuantities)

Batch updating location inventories and activate/deactivate inventories one by one complicate and slow down the process of synchronizing inventories per location. So adding bulk option for these operations will help us a lot to automate the stock update flow.

Not having batch/bulk operations support in the GraphQL API for such common use cases is a MAJOR oversight from the technical/product team.
 
We are also affected by this shortsightedness of the Shopify team in our effort to build automated stock update flows with our suppliers with catalogs of hundreds of thousands of products.

https://community.shopify.com/c/graphql-basics-and/graphql-bulkoperation-to-update-inventory-quantities/td-p/2078327

**Comment by oviliz** [comment]
wow... :(

**Comment by denizaygundev** [comment]
Not sure if it helps @oviliz @plesoiucosmin but I managed to set `inventoryItem` as tracked and set `inventoryQuantities` within a `productSet` bulk mutation https://shopify.dev/docs/api/admin-graphql/latest/mutations/productSet

It's working as expected for me

Edit - I guess your issue is specifically more around location activation

<img width="608" alt="Image" src="https://github.com/user-attachments/assets/28107d2d-e258-4b7e-8f20-73e1d6738995" />
