### ISSUE TITLE
RecurringApplicationCharge.current() does not work as expected

### ISSUE THREAD

**Issue by mentholi** [Shopify/shopify_python_api#85]
In RecurringApplicationCharge class there is class method "current" that doesn't work as expexted. 

## Problem
I have few RecurringApplicationCharge instances for my test shop but none of them has status=active. I was expecting to get None as a result when using current() method but instead a RecurringApplicationCharge with status rejected was returned.

```python
class RecurringApplicationCharge(ShopifyResource):

    @classmethod
    def current(cls):
        return cls.find_first(status="active")
```

## Excpected result 
First RecurringApplicationCharge object with status=active should be returned or None if no matches found. 

Anyway I noticed that documentation (http://docs.shopify.com/api/recurringapplicationcharge) states that it is only possible to filter with field "since_id". If this is correct, then this method should be removed.

**Comment by dylanahsmith** [comment]
I think this method was meant to do the same thing as the shopify_api ruby gem, which gets all the recurring application charges, then finds the active one from the in memory list of resources ([source](https://github.com/Shopify/shopify_api/blob/08a015701d828cc85e38eb5a232bbcfd54518983/lib/shopify_api/resources/recurring_application_charge.rb#L7)).  So this convenience method could be fixed in the same way.

**Comment by mentholi** [comment]
Hi, that's what I was thinking too. I will make a fix. Thanks for the help @dylanahsmith.
